### ISSUE TITLE
Show godmothers in the list of mentors

### ISSUE THREAD

**Issue by lilafisch** [chaosmentors/the-godmother#17]
We ended up forgetting to assign godmothers who were also willing to be mentors. However, there are also godmothers who will not be mentors, so we can't just add all godmothers to the mentors.

**Comment by famaniel** [comment]
Currently, there is just one integer value, that defines the role of a user: 1=Mentree 2=Mentor 3=Godmother. This means, you cannot be mentor and godmother at the same time. Therefore, if godmothers are to be mentors, the system needs to treat all godmothers as mentors. This is not the desired behaviour: Some people take the role of a godmother, but don't attend the event.

To reflect this in the model, I suggest separating the roles from the godmother status by extending the model with a boolean flag 
e.g. "isGodmother". Godmother features of the software can then be made available only to bearers of that flag (most other web software handles the adminstrator status like this). 

Further, I suggest adding the role 0=NotAttending, so someone who is not attending the event can still be in the system and be a godmother with out being accidentally added to a group. 

We should discuss whether allowing the status of isGodmother == true and role == mentee should be allowed. I believe it is not plausible, and should be prevented.

**Comment by lilafisch** [comment]
> We should discuss whether allowing the status of isGodmother == true and role == mentee should be allowed. I believe it is not plausible, and should be prevented.

I agree with this.

**Comment by famaniel** [comment]
I have split the godmother status off from the role. There still is a role "Godmother" which should be reserved for people, who are not mentors. See https://github.com/chaosmentors/the-godmother/pull/22 for details.
