### ISSUE TITLE
Transfer Issues from pattex/the-godmother - The easy way.

### ISSUE THREAD

**Issue by tewner** [chaosmentors/the-godmother#2]
Repository Contributors have an an option to "Transfer Issues" between repos.

Steps to transfer an Open issue to another repository

1. On GitHub, navigate to the main page of the repository.
2. Under your repository name, click Issues.
3. In the list of issues, click the issue you'd like to transfer.
4. In the right sidebar, click Transfer this issue.

**Comment by lilafisch** [comment]
I did not have this option, presumably because the repo is not owned by us.
