### ISSUE TITLE
Add Additional Documentation

### ISSUE THREAD

**Issue by tewner** [chaosmentors/the-godmother#20]
Things you may want to cover (original list from Pattex):

* Ruby version

* System dependencies

* Configuration

* Database creation

* Database initialization

* How to run the test suite

* Services (job queues, cache servers, search engines, etc.)

* Deployment instructions

**Comment by o1y** [comment]
We have a [readme](https://github.com/chaosmentors/the-godmother/blob/master/README.md), which should explain most of the important things.
