### ISSUE TITLE
Update the Contact Details on the "Contact" page

### ISSUE THREAD

**Issue by tewner** [chaosmentors/the-godmother#31]
We probably need to discuss these first, but these may not be relevant for this year:

via e-mail: chaosmentors [at] lists [dot] ccc [dot] de
via Twitter [@chaospatinnen](https://twitter.com/chaospatinnen)
via Mastodon: [@chaospatinnen@chaos.social](https://chaos.social/@chaospatinnen)

**Comment by famaniel** [comment]
The address was changed to chaosmentors [at] orca-central [dot] de
