### ISSUE TITLE
 add german version to sign up page

### ISSUE THREAD

**Issue by lilafisch** [chaosmentors/the-godmother#5]
we noticed that a lot of german speakers were very brief in their description text, and very few people filled the text in German. Our suspicion is that they thought they have to sign up in English. To make the chaos mentors more accessible to native German speakers, we should offer the sign up page in (at least ;) ) German and English.

**Comment by lilafisch** [comment]
this is being tackled in #19

**Comment by o1y** [comment]
Thanks, we've implemented a dedicated german translated sign up page.
